--- 
title: "Preprocessing" 
author: "livio e livio" 
date: "20/04/2022" 
output: 
  html_document: default 
  pdf_document:  
  toc: yes 
params: 
  tab_txt: "ID,Group      , Nuclei - Nucleus Length [µm],Nuclei - Intensity Nucleus HOECHST 33342 Mean,Nuclei - Nucleus Ratio Width to Length \n
1, G0          , 9 - 27, 300 - 900, 0.2 - 0.9\n
2, S           , 9 - 27, 900 - 1600, 0.2 - 0.9\n
3, G2 + early M, 12 - 27, 1600 - 3000, 0.2 - 0.9\n
4, M           , 8 - 12, 1600 - 3000, 0.2 - 0.9\n
5, Large       , 27 - Inf , 300 - 3000, 0.2 - 0.9\n
6, Small       , -Inf - 8  , 300 - 3000, 0.2 - 0.9\n
6, Small       , 8 - 9  , 300 - 1600, 0.2 - 0.9"
  PathData: "c('G:/My Drive/lavorincorso/brain_perm/pfas_tursiops_troncatus/data/Plate 1_19112021_ID457_Tm_P20_SingleData.csv',
              'G:/My Drive/lavorincorso/brain_perm/pfas_tursiops_troncatus/data/Plate 2_19112021_ID457_Tm_P21_SingleData.csv',
              'G:/My Drive/lavorincorso/brain_perm/pfas_tursiops_troncatus/data/Plate 3_19112021_ID457_Tm_P22_SingleData.csv',
              'G:/My Drive/lavorincorso/brain_perm/pfas_tursiops_troncatus/data/Plate 4_19112021_ID457_Tm_P24_SingleData.csv')" 
  eval_raw: "FALSE" 
--- 
 
```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = FALSE,warning = FALSE) 
# library(r41sqrt10) 
source('utils.R') 
source("functions.R") 
library(knitr)
``` 
 
# Import + preprocessing 
 
 
```{r Import_preprocessing} 
#ls() 
files=eval(parse(text=params$PathData)) 
filesRdata=gsub("csv","Rdata",files) 
 
eval_raw=eval(parse(text=params$eval_raw)) 
if(eval_raw){ 
  out=lapply(files,import_data_add_group,params$tab_txt) 
  D <- do.call("rbind", out) 
  rm(out) 
  D=D[D$Group!="0:None",]  
  D=D[D$Compound!="DMEM",] #"0:None" 
   
  D$Group=factor(D$Group) 
  D$Compound=factor(D$Compound) 
  D$Compound=relevel(D$Compound,"Control") 
  # contrasts(D$Compound) 
   
  D$Plate=factor(D$Plate) 
  D$Concentration=factor(D$Concentration) 
   
# D$Condition=factor(D$Condition) 
   
D$Column=factor(D$Column) 
D$Row=factor(D$Row) 
 
contrasts(D$Plate)=contr.sum 
contrasts(D$Column)=contr.sum(nlevels(D$Column)) 
contrasts(D$Row)=contr.sum(nlevels(D$Row)) 
 
 
  save(D, file= "datiD.Rdata") 
  } else   load("datiD.Rdata") 
``` 
```{r} 
 
# plot_row_data("13102021_ID429_Zm_P14_Plate1_SingleData.Rdata") 
# plot_row_data("13102021_ID429_Zm_P17_Plate2_SingleData.Rdata") 
# plot_row_data("13102021_ID429_Zm_P16_Plate3_SingleData.Rdata") 
# plot_row_data("13102021_ID429_Zm_P20_Plate4_SingleData.Rdata") 
``` 
 
```{r, eval=TRUE} 
Dall=c() 
 
for(i_fl in 1:length(filesRdata)){ 
  load(filesRdata[i_fl]) 
  dati$Plate=i_fl 
  Dall=rbind(Dall,dati) 
} 
 
Dall$Condition=apply(cbind(as.character(Dall$Compound), 
                        as.character(Dall$Concentration)), 
                  1,function(x) paste(x,collapse = ":")) 
Dall$Cond=factor(Dall$Condition)

Dall$ID=apply(cbind(as.character(Dall$Row), 
                        as.character(Dall$Column)), 
                  1,function(x) paste(x,collapse = ":")) 
Dall$ID=factor(Dall$ID)

``` 

## Number of Cells by Compound and Plate

```{r}
kable(table(Dall$Compound,Dall$Plate,exclude = NULL) )

```

NOTE: missing values are removed (why do they exist??)

```{r}
Dall=Dall[!is.na(Dall$Compound),]
```



# Descriptives


## Counts per Plates/coordinates

```{r}
tbs=table(Row=Dall$Row,Column=Dall$Column,Plate=Dall$Plate)

par(mfrow=c(2,2))
for(i in 1:4){
  cat("
  __________Plate ",i,"__________
      ") 
  print(kable(tbs[,,i]))
# #  print(kable(prop.table(tbs[,,i])))
# heatmap(tbs[,,i],Rowv = NA,Colv = NA,main=paste0("Plate ",i))  
}

tbs2=as.data.frame.table(tbs)

pp=lapply(1:4,function(i){
  ggplot(data=tbs2[tbs2$Plate==i,], aes(Row, Column, fill= Freq)) + 
  geom_tile()+ggtitle(paste0("Plate ",i))
  })

library(gridExtra) 
  grid.arrange(pp[[1]],pp[[2]],pp[[3]],pp[[4]], nrow = 2) 
  

```




## Groups by Plates

```{r}
tab=table(Dall$Group,Dall$Plate)
kable(tab) 

cat("NOTE: Category 0:None is omitted in the following")
Dall=Dall[Dall$Group!="0:None",]
Dall=Dall[!is.na(Dall$Group),]

Dall$Group=factor(Dall$Group)
tab=table(Dall$Group,Dall$Plate)

tab=prop.table(tab,margin = 2)
kable(tab,digits = 3) 

d_tab=as.data.frame.table(tab)
names(d_tab)=c("Group","Plate","Prop")

g <- ggplot(d_tab, aes(y=Plate))
g + geom_bar(aes(fill = Group,weight = Prop))+xlab("Proportion")+
  scale_fill_manual(values=cbPalette)

```

### Summary Features by Plates

```{r}

out=rbind(Nuclei_length=summary(Dall$Nuclei_length) ,
      Nuclei_intensity=summary(Dall$Nuclei_intensity) ,
      Nuclei_Ratio_W_L=summary(Dall$Nuclei_Ratio_W_L) 
)
out=cbind(out,c(sd(Dall$Nuclei_length) ,
              sd(Dall$Nuclei_intensity) ,
      sd(Dall$Nuclei_Ratio_W_L) )
)

kable(out)

p <- ggplot(Dall, aes(group=Plate, x=Plate,y=Nuclei_length,fill=2)) + 
  geom_boxplot()+ggtitle("Nuclei Length")+ theme(legend.position = "none")
p

p <- ggplot(Dall, aes(group=Plate, x=Plate,y=Nuclei_intensity,fill=2)) + 
  geom_boxplot()+ggtitle("Nuclei Intensity") + theme(legend.position = "none")
p
p <- ggplot(Dall, aes(group=Plate, x=Plate,y=Nuclei_Ratio_W_L,fill=2)) + 
  geom_boxplot()+ggtitle("Nuclei Ratio Width/Length") + theme(legend.position = "none")
p

```


## Conditions by Groups

```{r}

tab=table(Dall$Cond,Dall$Group)
kable(tab) 

cat("NOTE: Category 0:None is omitted in the following")
Dall=Dall[Dall$Group!="0:None",]
Dall=Dall[!is.na(Dall$Group),]

Dall$Group=factor(Dall$Group)
tab=table(Dall$Group,Dall$Cond)

tab=prop.table(tab,margin = 2)
kable(tab,digits = 3) 

d_tab=as.data.frame.table(tab)
names(d_tab)=c("Group","Condition","Prop")

g <- ggplot(d_tab, aes(y=Condition))
g + geom_bar(aes(fill = Group,weight = Prop))+xlab("Proportion")+
  scale_fill_manual(values=cbPalette)

```

## Explore variability of counts

```{r}
explore_control_group_plate_params(Dall,par_i = "Nuclei_intensity")
explore_control_group_plate_params(Dall,par_i = "Nuclei_length")
explore_control_group_plate_params(Dall,par_i = "Nuclei_Ratio_W_L")

```

```{r}
load("datiD.Rdata")
D$Condition=apply(cbind(as.character(D$Compound), 
                        as.character(D$Concentration)), 
                  1,function(x) paste(x,collapse = ":")) 
D$Cond=factor(D$Condition)

explore_control_group_plate(D)

```



## Scatter plot

```{r, eval=TRUE} 


Dall$Group0=Dall$Group 

table(Dall[Dall$Compound=="Control","Group"],exclude = NULL) 
my_plot1(Dall[Dall$Compound=="Control",]) 
 
# Dall$Group0=(Dall$Group=="0:None") 
# Dall$Group0=factor(Dall$Group0) 
# levels(Dall$Group0)=c("Grp 1-6","NO Grp") 
#  
# my_plot1(Dall) 
#my_plot2(Dall) 
 
``` 
 
